### ISSUE TITLE
Tab White Space issue.

### ISSUE THREAD

**Issue by ompatel11** [predatorx7/snake_code#1]
While using the Rich Text Editor I found out that when you try to use "\t" or Tab the line indicator does not follow the white spaces.
![Screenshot_1594911280](https://user-images.githubusercontent.com/58329791/87686891-b267d500-c7a2-11ea-953d-1e420b3ac2ba.png)

**Comment by predatorx7** [comment]
1. Where and how did you initialize the text controller? 
1. How did you add a tab-space?
1. Could you share the code related to this issue?

**Comment by ompatel11** [comment]
I declared the controller and in the initstate() added the printf() statement.

void initState() {
    super.initState();
    initSpeechRecognizer();
    controller = CreamyEditingController(
      // This is the CreamySyntaxHighlighter which will be used by the controller
      // to generate list of RichText.
      syntaxHighlighter: CreamySyntaxHighlighter(
        language: LanguageType.cpp,
        theme: HighlightedThemeType.darkTheme,
      ),
    );
    setState(() {
      controller.text =  '\tprintf("Hello world")';
    });
  }

**Comment by predatorx7** [comment]
I added a parameter in CreamyEditingField's constructor [set tab size](https://pub.dev/documentation/creamy_field/latest/creamy_field/CreamyEditingController/tabSize.html). Added properties to [replace \t with (spaces * tab size)](https://pub.dev/documentation/creamy_field/latest/creamy_field/CreamyEditingController/addTab.html).

For now, this is just a workaround. There is an ongoing issue on specifying tab spaces: https://github.com/flutter/flutter/issues/50087.

Released this fix in 0.3.1
