### ISSUE TITLE
onBackpress and onEnterPress is not fired

### ISSUE THREAD

**Issue by kedarkarkee** [predatorx7/snake_code#5]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Release & Debug Mode
    * Checked that your issue isn't already filed: <https://github.com/search?q=is%3Aissue+repo%3Apredatorx7%2Fsnake_code>

### Description

The onBackPress and onEnterPress methods aren't fired when backspace or enter key is pressed.
### Steps to Reproduce

1. Implement methods in SyntaxHighlighter class
2. Press backspace or enter in CreamyField
3. None of the events get triggered

**Expected behavior:**

The callback methods should be fired.

**Reproduces how often:**

100%

### Versions

0.3.2

**Comment by predatorx7** [comment]
Sorry, this won't be fixed. Please rely on the 'onChanged' parameter in the Text field.
