### ISSUE TITLE
Can't build on dev/master: ERROR: No named parameter with the name 'nullOk'.

### ISSUE THREAD

**Issue by esDotDev** [predatorx7/snake_code#6]
`MediaQuery.of(context, nullOk: true)` is the line, this has been deprecated it seems.

**Comment by predatorx7** [comment]
Can you point to the commit id, file name, and line number? OR just logs of the error.

**Comment by predatorx7** [comment]
I've looked in the code. I don't think it's deprecated in Flutter v1.22.4 stable.  I'd need logs and flutter doctor -v output to investigate more into the issue.

**Comment by esDotDev** [comment]
It's 901 in creamy_text_field.dart. Upgrade to master and you should see it
right away.

Looks like it's being removed in prep for null-safety:
https://docs.google.com/document/d/1LKBL0S1uyhACDiUXILhLKFZH8Cpl_w3mXjHgaE8_--U/edit#heading=h.pub7jnop54q0

**Comment by predatorx7** [comment]
Yeah, I know.. That's why asked your flutter doctor -v output too. It is not deprecated in Flutter v1.22.4 **stable**. You might be using Flutter on master. Tell me that and I'll make relevant changes.

**Comment by predatorx7** [comment]
Alright sorry. I missed the point where you mentioned youre using flutter master. I'll get this fixed.
